# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='season',
            field=models.IntegerField(default=0),
        ),
    ]
